/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: keiichiisozaki (https://sketchfab.com/keiichiisozaki)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/original-anime-girls-1b7084a8d4e04620879610059d98951c
Title: Original Anime Girls
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

import scene from '../assets/3d/animeGirls.glb'


const AnimeGirl = ({ currentAnimation, ...props}) => {
  const { nodes, materials } = useGLTF(scene);
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.girl_skin2_1.geometry}
          material={materials.mtl_skin2}
          scale={10.208}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.girl_face2_1.geometry}
          material={materials.mtl_face2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.girl_cloth2_1.geometry}
          material={materials.mtl_cloth2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.girl_hair_1.geometry}
          material={materials.mtl_hair}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.eyelash003_1.geometry}
          material={materials.white}
          position={[0, 0, 0.748]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.girl_skin_1.geometry}
          material={materials.mtl_skin}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.girl_cloth_1.geometry}
          material={materials.mtl_cloth}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.girl_face_1.geometry}
          material={materials.mtl_face}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pants2_1.geometry}
          material={materials.Root}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.girl_hair2_1.geometry}
          material={materials.mtl_hair2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pants_1.geometry}
          material={materials.white}
        />
      </group>
    </group>
  );
}

export default AnimeGirl;
